# Generated by Django 5.0.3 on 2024-03-09 01:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbot', '0002_user_chats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chats',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None),
        ),
    ]
